### ISSUE TITLE
Readme should be updated to assist Windows 11 24H2 users.

### ISSUE THREAD

**Issue by mayacaine** [Octanium91/NFS_Heat_CPU_Load_FIX#2]
With the release of Windows 11 24H2, Microsoft has stopped bundling WMIC out of the box on fresh installs due to it being utilised by some nefarious software, which has had the side effect of rendering this script nonfunctional. 

This can be fixed by running `DISM /Online /Add-Capability /CapabilityName:WMIC~~~~` before the script to reinstall it, allowing the script to work again, and I believe that stipulation should be added to the readme, as this could and almost certainly will avoid future confusion, given the only error visible when double clicking the script is `Oooops something went wrong :( (code: a)`. It may be worth updating the error code to specify this too, given a lot of people don't read readmes. It should also be noted that this *does* increase the attack surface of your system.

Thanks in advance!

**Comment by Octanium91** [comment]
Wooops

**Comment by Octanium91** [comment]
Thanks!

**Comment by sametaor** [comment]
Hi, it's still not mentioned in the readme, I found the solution right now by stumbling upon this.
Kindly either mention the fix or put a hyperlink to the following issue

**Comment by yurko251** [comment]
> With the release of Windows 11 24H2, Microsoft has stopped bundling WMIC out of the box on fresh installs due to it being utilised by some nefarious software, which has had the side effect of rendering this script nonfunctional.
> 
> This can be fixed by running `DISM /Online /Add-Capability /CapabilityName:WMIC~~~~` before the script to reinstall it, allowing the script to work again, and I believe that stipulation should be added to the readme, as this could and almost certainly will avoid future confusion, given the only error visible when double clicking the script is `Oooops something went wrong :( (code: a)`. It may be worth updating the error code to specify this too, given a lot of people don't read readmes. It should also be noted that this _does_ increase the attack surface of your system.
> 
> Thanks in advance!

please explain how to do this, I don't really understand how to do it and the script still doesn't work
